// This file was generated by Prisma
// Do not edit this file directly

import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    datasources: {
      db: {
        url: process.env.DATABASE_URL,
      },
    },
    log: process.env.NODE_ENV === "development" ? ["error", "warn"] : ["error"],
  });

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;

export const getTodaysAppointments = async () => {
  const istString = new Date().toLocaleString("en-US", {
    timeZone: "Asia/Kolkata",
  });
  const istDate = new Date(istString);

  const year = istDate.getFullYear();
  const month = istDate.getMonth();
  const date = istDate.getDate();

  const startOfDayUTC = new Date(Date.UTC(year, month, date, -5, -30, 0, 0));
  const endOfDayUTC = new Date(
    Date.UTC(year, month, date, 23 - 5, 59 - 30, 59, 999),
  );

  return await prisma.appointment.findMany({
    where: {
      appointmentDate: {
        gte: startOfDayUTC,
        lte: endOfDayUTC,
      },
    },
    include: {
      doctor: true,
      patient: true,
    },
    orderBy: {
      appointmentDate: "asc",
    },
  });
};

export const getTomorrowsAppointments = async () => {
  const istString = new Date().toLocaleString("en-US", {
    timeZone: "Asia/Kolkata",
  });
  const istDate = new Date(istString);
  istDate.setDate(istDate.getDate() + 1);

  const year = istDate.getFullYear();
  const month = istDate.getMonth();
  const date = istDate.getDate();

  const startOfDayUTC = new Date(Date.UTC(year, month, date, -5, -30, 0, 0));
  const endOfDayUTC = new Date(
    Date.UTC(year, month, date, 23 - 5, 59 - 30, 59, 999),
  );

  return await prisma.appointment.findMany({
    where: {
      appointmentDate: {
        gte: startOfDayUTC,
        lte: endOfDayUTC,
      },
      status: {
        not: "CANCELLED",
      },
    },
    include: {
      doctor: true,
      patient: true,
    },
    orderBy: [{ doctor: { name: "asc" } }, { appointmentDate: "asc" }],
  });
};
